env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
sudo: false
cache: bundler

jobs:
  include:
    - stage: python
      name: "Python tests"
      language: python
      python: "3.7"
      before_script:
        - pip install -r software/requirements.txt
      script: software/util/buildsite.py -r

    - stage: ruby
      name: "Ruby Linter"
      language: ruby
      rvm: 2.6
      env: SOFT_LINT=true
      before_install:
        - 'gem update --system --conservative || (gem i "rubygems-update:~>2.7" --no-document && update_rubygems)'
        - 'gem update bundler --conservative'
        - bundle install --gemfile=software/scripts/Gemfile
      before_script:
        - source ~/virtualenv/python3.7/bin/activate
        - pip install -r software/requirements.txt
        - software/util/buildsite.py -f Context RDFExport.nquads 
        - mkdir software/site/releases/LATEST
        - (cd software/site/releases/`software/util/schemaversion.py`; cp -r * ../LATEST)
        - deactivate
       
      script: (cd software/scripts; bundle exec rake)
